### ISSUE TITLE
what about adding a tunneling feature for more control and monitoring if everything is going as it should ?

### ISSUE THREAD

**Issue by minanagehsalalma** [h43z/dns-rebinding-tool#3]
just like what he wanted to do in the to do list in this article 
https://sinister.ly/Thread-DNS-Rebinding-Attack

> I need to make a tunnel (using JavaScript) to gain more control!

**Comment by h43z** [comment]
What is this tunneling?

**Comment by minanagehsalalma** [comment]
> tunneling?

Just like a command and control server

**Comment by h43z** [comment]
and what is tunneling in the context of dns rebinding?

**Comment by minanagehsalalma** [comment]
> and what is tunneling in the context of dns rebinding?

The ability of receiving and sending data/requests without the need of sending a new link for each one.

**Comment by h43z** [comment]
I have no idea what you are talking about. Explain what the fuck you want from this issue?! Like exactly and not something you overheard on some lame wanna be hacker forum.

**Comment by minanagehsalalma** [comment]
> Like exactly and not something you overheard on some lame wanna be hacker forum.

Haha that forum have very good quality for your information.

Here you go master very high level

https://portswigger.net/daily-swig/new-tool-enables-dns-rebinding-tunnel-attacks-without-reconnaissance

**Comment by h43z** [comment]
Nowhere in there it says how they do it or what the actual tunneling looks like.

**Comment by minanagehsalalma** [comment]
> Nowhere in there it says how they do it or what the actual tunneling looks like.

But it says how it should work or how it should be 
The repo
https://github.com/ReDTunnel

Is this half an hour video of it enough? 
https://youtu.be/sqUxeiqq0xE

**Comment by h43z** [comment]
What do you actually want from this issue?

**Comment by minanagehsalalma** [comment]
> What do you actually want from this issue?

One from what's in the video pls.

**Comment by h43z** [comment]
Again what do you want from this issue.
Put some effort into your response and make sure its proper English so I can understand you.

**Comment by minanagehsalalma** [comment]
> what do you want

Add command and control ability to the script.

**Comment by minanagehsalalma** [comment]
@h43z looks like Singularity supports it too

>Tunneling is implemented in Singularity. Check https://youtu.be/y9-0lICNjOQ?t=1326

**Comment by h43z** [comment]
Then use that tool. Or send PR.

**Comment by minanagehsalalma** [comment]
> send PR.

@h43z  I don't have the exact part of code where that is placed.



> Then use that tool

I do like to see how your port of it will look like   ...  also Singularity is a bit complicated.

**Comment by h43z** [comment]
too bad right

**Comment by minanagehsalalma** [comment]
> too bad right

Unfortunately ;(

**Comment by h43z** [comment]
Why u not write the code!?

**Comment by minanagehsalalma** [comment]
> Why you not write the code!?

Nope i didn't wrote it ... and that doesn't seem like proper English to me.

**Comment by h43z** [comment]
Why DO YOU not WRITE the CODE to DO THE STUFF you WANT it TO DO?

**Comment by minanagehsalalma** [comment]
> Why DO YOU not WRITE the CODE to DO THE STUFF you WANT it TO DO?

BECAUSE THAT WOULD TAKE SO FUCKIN LONG FROM ME I AM A NOOB IN PROGRAMMING.

**Comment by h43z** [comment]
You are an annoying script kiddy. Now go to your room and think about your behavior.

**Comment by minanagehsalalma** [comment]
> Now go to your room and think about your behavior.

@h43z  Lol think about my behavior?  It was better than yours 



> script kiddie

All i know is js i can't do match with it for now !

**Comment by asad0x01** [comment]
haha.



> Again what do you want from this issue.


** To get the breached data out of the iframe one could use Window.PostMessage() or include code that forwards the data to another attacker server within the script itself.**


thisˆˆ
