### ISSUE TITLE
DNS Rebinding protection bypass

### ISSUE THREAD

**Issue by minanagehsalalma** [h43z/dns-rebinding-tool#4]
@h43z  Yo bro , would these weird IP formatting be useful in bypassing dns rebinding protection/filters ?

https://blog.dave.tf/post/ip-addr-parsing/

just like the [CVE: 2020-26887
](https://www.redteam-pentesting.de/en/advisories/rt-sa-2020-003/-fritz-box-dns-rebinding-protection-bypass)
but more complicated.

**Comment by h43z** [comment]
I don't think so.
