### ISSUE TITLE
GPA game -  Please allow users to provide keys

### ISSUE THREAD

**Issue by JimmysDev** [h43z/dns-rebinding-tool#7]
Hi there,

Sorry for posting this on one of your other repos, I don't have twitter.

I found your game through LiveOverflow, I really want to play it but the rate limit is killing me. Please can you give users the ability to self host the game, or enter their own key like bettergpt.chat and slickGPT do. I realise this is potentially problematic, but it's better than letting it die. Plus you are fairly well known so one would hope you wouldn't steal the keys lol.

Anyway, thanks for your work, the game seems really fun from the first few levels I have played.

Feel free to close this

PS
now being rate limited 100% of the time, rip

**Comment by h43z** [comment]
yeah sorry. but it's expensive. Close #2
